monolog:
    channels: ['flight','exeception','instapago','payeezy','stripe']
    handlers:
        flight:
            level: debug
            type: rotating_file
            path: '%kernel.logs_dir%/flight/flight.log'
            max_files: 30
            channels: ["flight"]
        exeception:
            level: debug
            type: rotating_file
            path: '%kernel.logs_dir%/exeception/exeception.log'
            max_files: 30
            channels: ["exeception"]
        instapago:
            level: debug
            type: rotating_file
            path: '%kernel.logs_dir%/instapago/instapago.log'
            max_files: 30
            channels: ["instapago"]
        payeezy:
            level: debug
            type: rotating_file
            path: '%kernel.logs_dir%/payeezy/payeezy.log'
            max_files: 30
            channels: ["payeezy"]
        stripe:
            level: debug
            type: rotating_file
            path: '%kernel.logs_dir%/stripe/stripe.log'
            max_files: 30
            channels: ["stripe"]
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 30
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
