<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190719180107 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs

        $this->addSql("
            INSERT INTO payment_error (id, payment_type_id, code, name, gateway_message, message)
              VALUES 
                (nextval('payment_error_id_seq'), 3, 'approve_with_id', 'approve_with_id',
                'The payment cannot be authorized', 
                'El pago no puede ser autorizado'),
                (nextval('payment_error_id_seq'), 3, 'call_issuer', 'call_issuer',
                'The card has been declined for an unknown reason', 
                'Lo sentimos, tu tarjeta ha sido rechazada, intenta nuevamente con otra tarjeta o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'card_not_supported', 'card_not_supported',
                'The card does not support this type of purchase', 
                'La tarjeta no admite este tipo de compra'),
                (nextval('payment_error_id_seq'), 3, 'card_velocity_exceeded', 'card_velocity_exceeded',
                'The customer has exceeded the balance or credit limit available on their card', 
                'La tarjeta que utilizas no cuenta con fondo suficiente. Recarga tu saldo o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'currency_not_supported', 'currency_not_supported',
                'The card does not support the specified currency', 
                'La tarjeta no es compatible con la moneda especificada'),
                (nextval('payment_error_id_seq'), 3, 'do_not_honor', 'do_not_honor',
                'The card has been declined for an unknown reason', 
                'Lo sentimos, tu tarjeta ha sido rechazada, intenta nuevamente con otra tarjeta o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'do_not_try_again', 'do_not_try_again',
                'The card has been declined for an unknown reason', 
                'Lo sentimos, tu tarjeta ha sido rechazada, intenta nuevamente con otra tarjeta o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'duplicate_transaction', 'duplicate_transaction',
                'A transaction with identical amount and credit card information was submitted very recently', 
                'Una transacción con idéntica cantidad e información de tarjeta de crédito fue enviada muy recientemente'),
                (nextval('payment_error_id_seq'), 3, 'expired_card', 'expired_card',
                'The card has expired', 
                'Lo sentimos, tu tarjeta ha caducado'),
                (nextval('payment_error_id_seq'), 3, 'fraudulent', 'fraudulent',
                'The payment has been declined as Stripe suspects it is fraudulent', 
                'El pago ha sido rechazado ya que Stripe sospecha que es fraudulento'),
                (nextval('payment_error_id_seq'), 3, 'generic_decline', 'generic_decline',
                'The card has been declined for an unknown reason', 
                'Lo sentimos, tu tarjeta ha sido rechazada, intenta nuevamente con otra tarjeta o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'incorrect_number', 'incorrect_number',
                'The card number is incorrect', 
                'Los datos de tu tarjeta son inválidos, por favor verifícalos o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'incorrect_cvc', 'incorrect_cvc',
                'The CVC number is incorrect', 
                'El código CVC parece no estar correcto ¡Intenta colocarlo de nuevo!'),
                (nextval('payment_error_id_seq'), 3, 'insufficient_funds', 'insufficient_funds',
                'The card has insufficient funds to complete the purchase', 
                'La tarjeta que utilizas no cuenta con fondo suficiente. Recarga tu saldo o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'invalid_account', 'invalid_account',
                'The card, or account the card is connected to, is invalid', 
                'La tarjeta o la cuenta a la que está conectada no es válida'),
                (nextval('payment_error_id_seq'), 3, 'invalid_amount', 'invalid_amount',
                'The payment amount is invalid, or exceeds the amount that is allowed', 
                'El importe del pago no es válido o supera el importe permitido'),
                (nextval('payment_error_id_seq'), 3, 'invalid_cvc', 'invalid_cvc',
                'The CVC number is incorrect', 
                'El código CVC parece no estar correcto ¡Intenta colocarlo de nuevo!'),
                (nextval('payment_error_id_seq'), 3, 'invalid_expiry_year', 'invalid_expiry_year',
                'The expiration year invalid', 
                'La fecha de vencimiento de tu tarjeta no es correcta ¡Verifica tus fatos e intenta colocarla nuevamente!'),
                (nextval('payment_error_id_seq'), 3, 'invalid_expiry_month', 'invalid_expiry_month',
                'The expiration year invalid', 
                'La fecha de vencimiento de tu tarjeta no es correcta ¡Verifica tus fatos e intenta colocarla nuevamente!'),
                (nextval('payment_error_id_seq'), 3, 'invalid_number', 'invalid_number',
                'The card number is incorrect', 
                'Los datos de tu tarjeta son inválidos, por favor verifícalos o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'issuer_not_available', 'issuer_not_available',
                'The card issuer could not be reached, so the payment could not be authorized', 
                'No hemos podido establecer comunicación con el banco, por favor intenta más tarde'),
                (nextval('payment_error_id_seq'), 3, 'lost_card', 'lost_card',
                'The payment has been declined because the card is reported lost', 
                'El pago ha sido rechazado porque la tarjeta se informa perdida'),
                (nextval('payment_error_id_seq'), 3, 'merchant_blacklist', 'merchant_blacklist',
                'The payment has been declined because the card is reported lost', 
                'El pago se ha rechazado porque coincide con un valor en la lista de bloqueo del usuario de Stripe'),
                (nextval('payment_error_id_seq'), 3, 'new_account_information_available', 'new_account_information_available',
                'The card, or account the card is connected to, is invalid', 
                'Lo sentimos, tu tarjeta ha sido rechazada, intenta nuevamente con otra tarjeta o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'pickup_card', 'pickup_card',
                'The card cannot be used to make this payment (it is possible it has been reported lost or stolen)', 
                'La tarjeta no se puede usar para hacer este pago (es posible que se haya reportado como extraviada o robada)'),
                (nextval('payment_error_id_seq'), 3, 'processing_error', 'processing_error',
                'The card cannot be used to make this payment (it is possible it has been reported lost or stolen)', 
                'No pudimos procesar tu solicitud, por favor intenta nuevamente'),
                (nextval('payment_error_id_seq'), 3, 'reenter_transaction', 'reenter_transaction',
                'The payment could not be processed by the issuer for an unknown reason', 
                'No pudimos procesar tu solicitud, por favor intenta nuevamente'),
                (nextval('payment_error_id_seq'), 3, 'restricted_card', 'restricted_card',
                'The card cannot be used to make this payment (it is possible it has been reported lost or stolen)', 
                'La tarjeta no se puede usar para hacer este pago (es posible que se haya reportado como extraviada o robada)'),
                (nextval('payment_error_id_seq'), 3, 'revocation_of_all_authorizations', 'revocation_of_all_authorizations',
                'The card has been declined for an unknown reason', 
                'Lo sentimos, tu tarjeta ha sido rechazada, intenta nuevamente con otra tarjeta o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'revocation_of_authorization', 'revocation_of_authorization',
                'The card has been declined for an unknown reason', 
                'Lo sentimos, tu tarjeta ha sido rechazada, intenta nuevamente con otra tarjeta o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'security_violation', 'security_violation',
                'The card has been declined for an unknown reason', 
                'Lo sentimos, tu tarjeta ha sido rechazada, intenta nuevamente con otra tarjeta o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'service_not_allowed', 'service_not_allowed',
                'The card has been declined for an unknown reason', 
                'Lo sentimos, tu tarjeta ha sido rechazada, intenta nuevamente con otra tarjeta o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'stolen_card', 'stolen_card',
                'The payment has been declined because the card is reported stolenn', 
                'El pago ha sido rechazado porque la tarjeta ha sido reportada como robada'),
                (nextval('payment_error_id_seq'), 3, 'stop_payment_order', 'stop_payment_order',
                'The card has been declined for an unknown reason', 
                'Lo sentimos, tu tarjeta ha sido rechazada, intenta nuevamente con otra tarjeta o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'testmode_decline', 'testmode_decline',
                'A Stripe test card number was used', 
                'Se utilizó un número de tarjeta de prueba'),
                (nextval('payment_error_id_seq'), 3, 'transaction_not_allowed', 'transaction_not_allowed',
                'The card has been declined for an unknown reason', 
                'Lo sentimos, tu tarjeta ha sido rechazada, intenta nuevamente con otra tarjeta o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'try_again_later', 'try_again_later',
                'The card has been declined for an unknown reason', 
                'Lo sentimos, tu tarjeta ha sido rechazada, intenta nuevamente con otra tarjeta o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'withdrawal_count_limit_exceeded', 'withdrawal_count_limit_exceeded',
                'The customer has exceeded the balance or credit limit available on their card', 
                'La tarjeta que utilizas no cuenta con fondo suficiente. Recarga tu saldo o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'amount_too_large', 'amount_too_large',
                'The specified amount is greater than the maximum amount allowed', 
                'La cantidad especificada es mayor que la cantidad máxima permitida'),
                (nextval('payment_error_id_seq'), 3, 'amount_too_small', 'amount_too_small',
                'The specified amount is less than the minimum amount allowed', 
                'La cantidad especificada es menor que la cantidad mínima permitida'),
                (nextval('payment_error_id_seq'), 3, 'api_key_expired', 'api_key_expired',
                'The API key provided has expired', 
                'No hemos podido establecer comunicación con el banco, por favor intenta más tarde'),
                (nextval('payment_error_id_seq'), 3, 'balance_insufficient', 'balance_insufficient',
                'The transfer or payout could not be completed because the associated account does not have a sufficient balance available. Create a new transfer or payout using an amount less than or equal to the account’s available balance', 
                'La tarjeta que utilizas no cuenta con fondo suficiente. Recarga tu saldo o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'card_declined', 'card_declined',
                'The card has been declined', 
                'Lo sentimos, tu tarjeta ha sido rechazada, intenta nuevamente con otra tarjeta o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'instant_payouts_unsupported', 'instant_payouts_unsupported',
                'This card is not eligible for Instant Payouts. Try a debit card from a supported bank', 
                'Por favor, conmunícate con tu banco y activa tu tarjeta para pagos instantáneos'),
                (nextval('payment_error_id_seq'), 3, 'processing_error', 'processing_error',
                'An error occurred while processing the card. Check the card details are correct or use a different card', 
                'Lo sentimos, tu tarjeta ha sido rechazada, intenta nuevamente con otra tarjeta o realiza una transferencia bancaria'),
                (nextval('payment_error_id_seq'), 3, 'url_invalid', 'url_invalid',
                'The URL provided is invalid', 
                'No hemos podido establecer comunicación con el banco, por favor intenta más tarde');
        ");

    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
